# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Obtains likelihood
#' Calculates likelihood from observed outcome data and given covariate data/parameters.
#' @param Y Binary outcome vector.
#' @param X Matrix of covariates.
#' @param beta0 Intercept parameter.
#' @param beta Vector of covariate parameters of length p.
#' @return Likelihood
#' @useDynLib VARSELECTEXPOSURE
#' @export
LIKE <- function(Y, X, beta0, beta) {
    .Call('_VARSELECTEXPOSURE_LIKE', PACKAGE = 'VARSELECTEXPOSURE', Y, X, beta0, beta)
}

